### ISSUE TITLE
Add the Profile Registration to the Huxley API and CLI

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#43]
In order to not have the user pass their credentials every time they make a request with the CLI, please establish the resource "User" with Huxley.  

On the CLI, the user can use the command `huxley user register`.  An interviewer will accept several pieces of information:
- email address
- AWS ID
- AWS secret key

The Huxley API server stores these, generates a secret token and returns that to the CLI where it is stored in the local machine's home configuration (Huxley dotfile).  That token is what the user will need for all future commands.

**Comment by dyoder** [comment]
This is a good requirement, in the right milestone. I think it makes sense at this point to get registration working. A couple of notes.

We [don't call people users](https://www.pandastrike.com/posts/20150219-personas-not-users). :)

Instead, please use the word _profile_.

```
huxley profile create
```

The command should take an optional name (for the profile; later we'll support multiple profiles). With no name, it should create a `default` profile. If a default profile already exists, we should error out with an error message. Developers can remove a profile with:

```
huxley profile rm personal
```

and start over.

Since AWS credentials are things you probably aren't going to type, I don't think using an interviewer makes sense here. Instead, we should try to get them from their AWS config (see #51) or from the command line as options. Ex:

```
huxley profile create --email=dan@pandastrike.com
```

which would create a default profile, associate it with the email `dan@...`, and (attempt to) pull the AWS credentials from my ~/.aws directory.

**Comment by dyoder** [comment]
Also: we don't need to store these on the server to add them to the CLI. Please split this into two tickets.
