### ISSUE TITLE
Setup the Huxley API for Manual Docker Container Deployment

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#92]
Since we are transitioning to use of Redis with the Huxley API for message queueing and DB function, we should move to a Dockerized deployment.  Please prepare containers for the Huxley API and its Redis companion.

Even though the eventual goal is the automated deployment of the Huxley API, for now please just focus on a manual Dockerized deployment.  Please include any additional instructions in the API server wiki section.

**Comment by PandaWhisperer** [comment]
Got a basic `Dockerfile` ready to go. The main problem is connecting the `ssh-agent`. 

Found [these instructions](https://gist.github.com/d11wtq/8699521) and will try them out.

**Comment by PandaWhisperer** [comment]
Alright. Just verified with @PandaPup that mapping the local agent into the container isn't actually necessary.

I figured out how to [link to containers together for networking purposes](https://docs.docker.com/userguide/dockerlinks/). Will update the wiki with instructions.

**Comment by PandaWhisperer** [comment]
Alright. Wiki is updated. Just one thing left to do: when using Docker, mutual needs to be pointed to the correct hostname instead of `localhost`. In other words, we'll need add an extra step to the setup. 

**OR**

We could add this step to the `Dockerfile`, meaning that every Docker image we produce would be properly preconfigured. I think I like the latter more.

**Comment by PandaWhisperer** [comment]
Alright, I implemented the latter. Will add a PR now.

**Comment by PandaWhisperer** [comment]
Okay, I'm all set up to push docker images to the hub. As soon as we wrap up our release, I can put them live.
